### ISSUE TITLE
Typo on the page

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#11]
Issue in ./help/troubleshooting/miscellaneous/adobe-commerce-244-update-composer.md

This articles provides a solution to avoid the issue with composer plugins when upgrading from Adobe Commerce 2.4.3 and **erlier** to Adobe Commerce 2.4.4 or higher (when future versions are released).

This should be ``earlier``

**Comment by Rinn22** [comment]
jira ticket: https://jira.corp.adobe.com/browse/MSKB-1883

**Comment by barnato-v** [comment]
@ak77-prime Hi Anthony thanks for spotting this typo.

**Comment by barnato-v** [comment]
@ak77-prime I made this update in a PR in the enterprise/internal repo here https://git.corp.adobe.com/AdobeDocs/commerce-knowledge-base.en/pull/94
I am now going to close this issue https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/adobe-commerce-244-update-composer.html?lang=en
