### ISSUE TITLE
Update the disconnection verbiage

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#13]
Issue in ./help/troubleshooting/miscellaneous/cannot-access-the-correct-cloud-project.md

Currently in Step 2 of the Solution:

``Click Disconnect from Magento.com to disconnect.``

To be changed to:

``Click Disconnect from Adobe.com to disconnect.``

Also, the image needs to be updated accordingly, e.g.,

![image](https://user-images.githubusercontent.com/68703716/200638457-d0692c9e-ac98-463b-9ab3-f43f51edd69f.png)

**Step 2.**

![image](https://user-images.githubusercontent.com/68703716/200638124-d509fc9e-d0a2-4d6c-8531-31a3e5a1d971.png)

**Comment by Rinn22** [comment]
Jira ticket: https://jira.corp.adobe.com/browse/MSKB-1885

**Comment by barnato-v** [comment]
@ak77-prime Hi Anthony, 

Thank you for this. I wanted to check that all images and text had been identified in the article that needed to be rebranded.

1) Shouldn't all three images be replaced? So yes the first image that has the text "Provide: Magento.com - status Connected as MAG" and Disconnect from Magento.com. But also does the second image with the text "Connect with Magento.com" not need to be replaced or was this part of the UI not rebranded yet? Same question for the third image - should it be rebranded as the fourth button under the text "Log in" in that image says "Magento.com"
2) What about "Magento" being used in the text of step 4; "_Now click on the Magento.com button._".? Should that be removed

**Comment by ak77-prime** [comment]
Replace Magento.com with Adobe.com for all of them

**Comment by barnato-v** [comment]
> Replace Magento.com with Adobe.com for all of them

Hi @ak77-prime Would it be possible for you to attach the other two replacement pngs to the following Jira ticket https://jira.corp.adobe.com/browse/MSKB-1885?

When I log in I am afraid I do not get the right images so can't take screen shots

**Comment by barnato-v** [comment]
PR https://github.com/AdobeDocs/commerce-knowledge-base.en/issues/13

**Comment by barnato-v** [comment]
Changes made in the published article https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/cannot-access-the-correct-cloud-project.html?lang=en#cause
