### ISSUE TITLE
Add more information and clarify some nomenclature

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#14]
Issue in ./help/troubleshooting/miscellaneous/cannot-access-magento-commerce-cloud-ui.md

Problem:
If you have never visited the Cloud UI before, going to the URL will load the master branch. 

Solution
If you are getting a 403 error when accessing the URL for the first time, make sure that you have a role in the master branch. 

1. Сontact the project owner or a Super User on the project and make sure they provided access to you as an environment-level user, also described in [Cloud projects > Manage users from the Project Web UI](https://devdocs.magento.com/cloud/project/user-admin.html#cloud-user-webinterface) in our developer documentation.

If you only have an applicable role in a specific branch, then you would need to go to the URL for that branch, e.g., https://region.magento.cloud/projects/PROJECTID/environments/allowed_branch

The next time you access the main URL, it will default to the last environment you've visited

2. If you still cannot log in, сontact the license owner or Super User on the project and make sure they provided access for you as a project-level user, as described in step 5 of Manage user access to [Cloud projects > Manage users from the Project Web UI](https://devdocs.magento.com/cloud/project/user-admin.html#cloud-user-webinterface) in our developer documentation.

3. If the error persists, [submit a support ticket](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html?lang=en#submit-ticket).

Source/example issue:  https://magento.zendesk.com/agent/tickets/573703

**Comment by Rinn22** [comment]
jira ticket: https://jira.corp.adobe.com/browse/MSKB-1884

**Comment by ak77-prime** [comment]
> jira ticket: https://jira.corp.adobe.com/browse/MSKB-1884

that's not the same issue

**Comment by Rinn22** [comment]
Thank you Anthony. The ticket is solved. Closing this issue.
