### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by lily-awilloughby** [AdobeDocs/commerce-knowledge-base.en#15]
Issue in ./help/announcements/adobe-commerce-announcements/2021-holiday-surge-capacity-requests-for-magento-commerce-cloud.md

Broken link in 'Planning and Estimating Traffic' section - https://business.adobe.com/blog/how-to/five-ps-peak-season-performance-guide-preparing-your-infrastructure-high

**Comment by Rinn22** [comment]
jira ticket: https://jira.corp.adobe.com/browse/MSKB-1887

**Comment by barnato-v** [comment]
@lily-awilloughby thanks very much for letting us know. The link has been fixed on the article https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/announcements/commerce-announcements/2021-holiday-surge-capacity-requests-for-magento-commerce-cloud.html
