### ISSUE TITLE
Adding another cause for the issue

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#16]
Issue in ./help/troubleshooting/miscellaneous/cannot-access-the-correct-cloud-project.md

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/cannot-access-the-correct-cloud-project.html?lang=en#cause

Another possible cause:
You have changed your email address at https://account.adobe.com to another email address that is not currently associated with a Cloud Project.

Solution for this additional cause: 

Ask an existing Super User on the project to [add your new email address](https://devdocs.magento.com/cloud/project/user-admin.html) to the project

**Comment by barnato-v** [comment]
Cause was added here https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/cannot-access-the-correct-cloud-project.html?lang=en#cause
