### ISSUE TITLE
incomplete command

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#20]
Issue in ./help/troubleshooting/miscellaneous/magento-advanced-reporting-troubleshooter.md

On **Step 9**, this command is missing the project ID:

``zgrep -i analytics /var/log/platform//access.log* | grep MagentoBI``

It should be:

``zgrep -i analytics /var/log/platform/[cluster_id|cluster_id_stg]/access.log* | grep MagentoBI``

**Comment by barnato-v** [comment]
@ak77-prime Thank you for this. Here is the Jira ticker https://jira.corp.adobe.com/browse/MSKB-1959

**Comment by barnato-v** [comment]
@ak77-prime I have corrected the code in this PR here and in the internal repo. Thanks again. https://git.corp.adobe.com/AdobeDocs/commerce-knowledge-base.en/pull/167
