### ISSUE TITLE
Additional notes for the Organization field

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#21]
Issue in ./help/help-center-guide/help-center/magento-help-center-user-guide.md

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html?lang=en#ticket-fields-explained > Organization field

Under the ``warning`` message, add a new note that the organization can be changed later 

To change the Organization after the ticket has been submitted, in the right column of the ticket, locate the dropdown for the available Organizations - you will be able to re-select the appropriate one here.

**Example only:**
![image](https://user-images.githubusercontent.com/68703716/210657444-0efb725e-84a7-468e-87ff-ee6d679dc6a2.png)

**Comment by barnato-v** [comment]
@ak77-prime Hi Anthony, thanks for this. I have created a Jira ticket and assigned it https://jira.corp.adobe.com/browse/MSKB-1960

**Comment by barnato-v** [comment]
@ak77-prime and @tanay-sharma Looks like this is complete https://jira.corp.adobe.com/browse/MSKB-1960 - so closing this issue. Thanks.
