### ISSUE TITLE
Invalid Link at Backup (snapshot) on Cloud: FAQ

### ISSUE THREAD

**Issue by aabumuslimov** [AdobeDocs/commerce-knowledge-base.en#23]
Issue in ./help/faq/general/backup-snapshot-on-cloud-faq.md

> Retention time for automatic snapshots is different and follows [the schedule](https://devdocs.magento.com/guides/v2.2/cloud/architecture/pro-architecture.html#backup-and-disaster-recovery).

Link "the schedule" points to -> Page Not Found : https://devdocs.magento.com/guides/v2.4/cloud/architecture/pro-architecture.html#backup-and-disaster-recovery

**Comment by barnato-v** [comment]
@aabumuslimov I assume that this is the replacement link but I will investigate with the devdocs team https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/architecture/pro-architecture.html?lang=en#backup-and-disaster-recovery

**Comment by barnato-v** [comment]
@aabumuslimov Hi! I made the change in an internal PR - the link is now fixed here https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/architecture/pro-architecture.html?lang=en#backup-and-disaster-recovery
