### ISSUE TITLE
No buttons with headings to get anchor link to that part of the doc

### ISSUE THREAD

**Issue by ebachmeier** [AdobeDocs/commerce-knowledge-base.en#24]
Issue in ./help/troubleshooting/miscellaneous/low-disk-space.md

On the older version of the commerce docs, you used to be able to click a small link button by headings to get the anchor link to that part of the page. It is very useful functionality that I think should be brought back as docs are all moving over to experience leaque Adobe docs it seems.

![image](https://user-images.githubusercontent.com/28953683/217279152-3521aeed-1451-425c-8cff-c407916d1c78.png)

**Comment by barnato-v** [comment]
@ebachmeier Hi @ebachmeier Have you tried using the "On this page" heading links

<img width="460" alt="image" src="https://user-images.githubusercontent.com/60674257/217682950-e7ce1d77-da2b-49a8-94a5-8bc425fe2d61.png">
