### ISSUE TITLE
Update affected versions to include 2.4.x

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#3]
Issue in ./help/troubleshooting/deployment/magento-commerce-cloud-repo-could-not-be-accessed-403-forbidden-or-404-not-found-error-when-deploying.md

**Affected products and versions**
Adobe Commerce on cloud infrastructure 2.2.x, 2.3.x, **2.4.x**

**Comment by tanay-sharma** [comment]
Thanks, @ak77-prime. I have created a ticket for this: https://jira.corp.adobe.com/browse/MSKB-1835

**Comment by tanay-sharma** [comment]
Updated
