### ISSUE TITLE
WHY??? why sensitive credentials can only be commited? why it doesn't work as environmental variable???

### ISSUE THREAD

**Issue by artissegrums** [AdobeDocs/commerce-knowledge-base.en#31]
Issue in ./help/how-to/general/redeploy-with-another-key.md

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/how-to/redeploy-with-another-key.html?lang=en

**Comment by ahmed-saeed-masry** [comment]
Is there any updates here? I have same issue!

**Comment by jmenn** [comment]
Hi @artissegrums and @ahmed-saeed-masry!
Thank you for your feedback!

To get an answer to your questions, you will need to open a ticket in the Adobe Commerce Help Center by following [these instructions in the Help Center User Guide](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html?lang=en#support-tickets).

Thank you again!

**Comment by jmenn** [comment]
If you want more places to ask, the other locations I can direct you to are the Adobe Forums, and the Magento2 GitHub:

https://community.magento.com/
https://github.com/magento/magento2
