### ISSUE TITLE
I cannot open a new ticket

### ISSUE THREAD

**Issue by MattSabbatini** [AdobeDocs/commerce-knowledge-base.en#34]
Issue in ./help/help-center-guide/help-center/magento-help-center-user-guide.md
<img width="1374" alt="Screenshot 2023-04-28 alle 10 52 24" src="https://user-images.githubusercontent.com/105279129/235102149-80c61503-9194-4bbe-9bd7-452cd6a1c236.png">

As you can see in both images, the layout of my help center is different from what I've found on the documentation, mainly it is missing the "submit a new ticket" CTA, even when I'm logged in, as in the case of the screenshoot. 
On the second one i tried using https://experienceleague.adobe.com/, but still won't let me. 
<img width="673" alt="Screenshot 2023-04-28 alle 10 52 00" src="https://user-images.githubusercontent.com/105279129/235102188-8089444e-1821-4154-95f0-22c8fbde3fbe.png">

**Comment by jmenn** [comment]
Hello @MattSabbatini,
Thank you for reaching out.
Unfortunately, this is not a portal that is monitored by Support engineers.

The original page you went to (https://support.magento.com/hc/en-us) has the blue banner at the top that directs you to our new home where it says, "Click 'Support Knowledge Base' (https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/overview.html) to access our new Knowledge Base Home." 

Our new home (https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/overview.html) has the "Help Center User Guide" (https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html) linked off of it.

In the "Help Center User Guide" (https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html) table of contents, please see the 
"Log In To Help Center"(https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html?lang=en#login)
and
"Submit a support ticket" (https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html?lang=en#submit-ticket)

----If you have followed those instructions completely, and still do not see the "Submit a Ticket" button on your page as shown in the "Help Center start page" screenshot, 
then please follow the instructions on the section titled, 
"'Submit a ticket' link not displayed on Adobe Commerce Help Center start page" on the "Help Center User Guide" (https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html) page.

We hope this helps!
