### ISSUE TITLE
Double billed

### ISSUE THREAD

**Issue by CLGrant11** [AdobeDocs/commerce-knowledge-base.en#36]
Issue in ./help/support-tools/patches-available-in-qpt-tool/v1-0-7/mdva-31282-magento-patch-double-authorization-on-paypal-payflow-pro.md

I have been double billed in the amount of 13.64 (x7) the last 7 months.  Please point me in the direction to have this rectified as I can find no portals for an actual Adobe customer service.

**Comment by barnato-v** [comment]
@CLGrant11 Hello,

Please refer to steps on how to submit a ticket here for Adobe Commerce https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/help-center-guide/magento-help-center-user-guide.html?lang=en#submit-ticket
