### ISSUE TITLE
Title in browser window includes the *

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#38]
Issue in ./help/troubleshooting/miscellaneous/file-cannot-be-deleated-no-file-or-directory.md

The page title includes the asterisk that's included in the content:

[*The file can't be deleted. Warning! unlink: No such file or directory error* from the Admin | Adobe Commerce](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/file-cannot-be-deleated-no-file-or-directory.html?lang=en)

**Comment by barnato-v** [comment]
https://git.corp.adobe.com/AdobeDocs/commerce-knowledge-base.en/pull/500
