### ISSUE TITLE
Using du -x is suboptimal for the Pro architecture layout

### ISSUE THREAD

**Issue by alanbort** [AdobeDocs/commerce-knowledge-base.en#39]
Issue in ./help/troubleshooting/miscellaneous/safely-delete-files-when-out-of-disk-space-adobe-commerce-on-our-cloud-architecture.md

The reported script is using du -x, which isolates the DU operation to a single filesystem, this excludes the most likely space consumers from `pub/media` and `pub/static` on Pro clusters, which use GlusterFS and have separate filesystems for each of those persistent directories.

**Comment by Rinn22** [comment]
Hey @alanbort, so is there any change we should make in the script?

**Comment by barnato-v** [comment]
@Rinn22 Hi Rinn,

I have reached out to the SME who has been a contributor on this article to confirm if the script should be changed.

**Comment by barnato-v** [comment]
@alanbort Thanks for all your help with this Alan. The change was made to the published article here https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/safely-delete-files-when-out-of-disk-space-adobe-commerce-on-our-cloud-architecture.html

Closing this issue now and associated Jira https://jira.corp.adobe.com/browse/MSKB-2355
