### ISSUE TITLE
Deprecated article/version

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#40]
Issue in ./help/troubleshooting/miscellaneous/error-running-the-setup-di-compile-command-manually.md

This only applies to Commerce on Cloud infrastructure 2.0 and 2.1 - which are no longer supported, together with 2.2 and 2.3 - so this article is no longer valid and should be removed/archived.

**Comment by Viper9x** [comment]
@ak77-prime This documentation indicates that the affected versions are Adobe Commerce on cloud infrastructure 2.0.X, 2.1.X.
> Affected versions
> - Adobe Commerce on cloud infrastructure 2.0.X, 2.1.X

Therefore it should be preserved and not removed.

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/error-running-the-setup-di-compile-command-manually.html

@jeff-matthews Can you confirm that this documentation should not be archived or removed?

**Comment by jeff-matthews** [comment]
@Viper9x, I can see how this might be useful info to preserve, but I defer to the maintainers of this repo.

It makes me wonder though, what are the odds that someone on Adobe Commerce cloud hosting is running a version of core earlier than 2.3.x? I thought there were mechanisms in place to ensure cloud customers were at least on a supported version, but I might be mistaken.

**Comment by almarchenko** [comment]
We will archive it. 
Created an internal ticket for this. Will let you know once done.

**Comment by tanay-sharma** [comment]
Article archived.
