### ISSUE TITLE
Version Typo

### ISSUE THREAD

**Issue by Nurgiel** [AdobeDocs/commerce-knowledge-base.en#41]
Issue in ./help/support-tools/patches-available-in-qpt-tool/v1-1-34/acsd-51857-slow-cron-job-of-aggregate-sales-report-bestsellers-data-affects-performance.md

Quote:
The patch ID is ACSD-51857. Please note that the issue was fixed in Adobe Commerce 2.4.7.
(...)
Compatible with Adobe Commerce versions:
    Adobe Commerce (all deployment methods) 2.4.0 - 2.4.6-p1

Problem:
It should say 2.4.0 - 2.4.6-p2 instead of -p1

**Comment by barnato-v** [comment]
@Nurgiel Thank you so much for noticing this and telling us. We have created a Jira ticket for this and assigned to an author have the change made. We will let you know when complete.

**Comment by barnato-v** [comment]
@Nurgiel Hello Nurgiel, thank you so much for this suggestion. As you can see change was made to the article here https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-34/acsd-51857-slow-cron-job-of-aggregate-sales-report-bestsellers-data-affects-performance.html

**Comment by Viper9x** [comment]
@barnato-v, since Adobe Commerce and Magento Open Source released a new version yesterday, the compatible with Adobe Commerce versions information should be updated from

> Adobe Commerce (all deployment methods) 2.4.0 - 2.4.6-p2
to
> Adobe Commerce (all deployment methods) 2.4.0 - 2.4.6-p3

**Comment by almarchenko** [comment]
@Viper9x  thank you for you input!
We have a note in each of the QPT articles mentioning, that a patch might be compatible with other versions. But at this very moment we don't have a policy of going back and updating the specific compatibility version, it is usually specified as it was on the moment of publication (unless we get specific requests for updates from the QPT release team).

**Comment by Viper9x** [comment]
@almarchenko I have raised this issue because you guys have updated the information to include 2.4.6-p2. Anyway, never mind, I'm happy with the current information.
