### ISSUE TITLE
Proposal for new article - Issues with Slave Reads and Replication Synchronization with MariaDB 10.6

### ISSUE THREAD

**Issue by alanbort** [AdobeDocs/commerce-knowledge-base.en#44]
This is a proposal for a new article for a recent issue that appeared with upgrades to 2.4.6 which require MariaDB 10.6

1. Symptoms

Customers may experience inconsistent outcomes when reading data immediately after saving it when using Read Replicas on Adobe Commerce Cloud 2.4.6 with MariaDB 10.6+

What we notice is that sometimes the load is not returning the existing data in the database for the saved entity with this issue. The data is there and load just a tiny bit later is successful even within the same transaction.

2. Resolution

The resolution discussion for the issue is on  MCLOUD-10781 - MariaDB synchronous/asynchronous replication configuration TRIAGE

Replication configuration: Ensure the `slave_parallel_mode` parameter is set to `conservative`. Raise a support ticket if this is not the case.

```
MariaDB [main]> show variables like 'slave_parallel_mode';
+---------------------+--------------+
| Variable_name       | Value        |
+---------------------+--------------+
| slave_parallel_mode | conservative |
+---------------------+--------------+
1 row in set (0.001 sec)
```

Replication configuration in ENV: Update `.magento.env.yaml` as shown below

```
DATABASE_CONFIGURATION:
    _merge: true
        slave_connection:
            default:
                synchronous_replication: false
```

**Comment by barnato-v** [comment]
@alanbort Thank you so much for your suggested new article Alan. I have create a Jira here https://jira.corp.adobe.com/browse/MSKB-2430 for the new article and it will be discussed and assigned to an author in our weekly KB writer meeting.

**Comment by barnato-v** [comment]
First draft in PR here https://git.corp.adobe.com/AdobeDocs/commerce-knowledge-base.en/compare/MSKB-2430?expand=1

**Comment by barnato-v** [comment]
Article published here https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/database/read-replicas-issues-synchronization-mariadb-10-6.html?lang=en @alanbort thank you so much for your help on this!
