### ISSUE TITLE
Incorrect redirect to Experience League on article Max sales rules best practice in Adobe Commerce 

### ISSUE THREAD

**Issue by mladobe** [AdobeDocs/commerce-knowledge-base.en#45]
Hi team,
we have an article in the old doco here https://support.magento.com/hc/en-us/articles/360045957511-Max-sales-rules-best-practice-in-Adobe-Commerce that has a link to "the same article on Experience league" pointing here: https://experienceleague.adobe.com/docs/commerce-operations/implementation-playbook/best-practices/planning/catalog-management.html?lang=en but that's not the same article.

Could we create or find the correct article on sales rule limitations as we've had a couple of customers trying to find that info.

thanks

**Comment by almarchenko** [comment]
Hi @mladobe ! 
I think the developer docs team has updated the article according to the latest guidelines from the product team. I think customers should contact CSMs or TAMs with those questions. @jeff-matthews  do you have anything additional to add perhaps? 
TY

**Comment by jeff-matthews** [comment]
@almarchenko

Yes, you're correct. Detailed info can be found in the COMDOX-760 Jira ticket assuming that @mladobe is an Adobe employee and has access to Jira.

**Comment by mladobe** [comment]
Thanks all - will check the Jira
