### ISSUE TITLE
Import Adobe Commerce Code into a Cloud project > Import Adobe Commerce database link is 404

### ISSUE THREAD

**Issue by denysbabenkodivae** [AdobeDocs/commerce-knowledge-base.en#48]
Issue in ./help/how-to/general/sync-data-and-files-from-production-to-staging-or-staging-to-integration.md

https://experienceleague.adobe.com/de/docs/commerce-cloud-service/user-guide/develop/deploy/staging-production lands on 404

**Comment by jmenn** [comment]
Hi @denysbabenkodivae! 

We'll take a look what's happening with the German translation of that page.

Meanwhile, if you understand English, or use a translator on the page, the English version of that page is up and accessible here:
https://experienceleague.adobe.com/en/docs/commerce-cloud-service/user-guide/develop/deploy/staging-production

**Comment by jmenn** [comment]
Hi @denysbabenkodivae!

This article on the link you provided now loads.

Thanks for reaching out!
