### ISSUE TITLE
Duplicate steps? 

### ISSUE THREAD

**Issue by JeffGreenlee42** [AdobeDocs/commerce-knowledge-base.en#50]
Issue in ./help/how-to/general/upgrade-mariadb-10-4-to-10-5-for-magento-commerce-cloud.md

I am submitting this as myself because I do not have a github profile under my Adobe Alias jgreenlee@adobe.com

We (in Adobe Sandbox support) sent out an email to SPP partners with older versions of Commerce that MariaDB will end support for ealier versions. I got feedback that Steps  1, 4 and 5b appear to be duplicate steps.  Perhaps an explanation in this document for this is warrented?

**Comment by Nayanika30185** [comment]
Thank you for reporting this! 
We have created a JIRA to have this resolved - https://jira.corp.adobe.com/browse/MSKB-2647

**Comment by Nayanika30185** [comment]
Hi Jeff, a note has been added to the article addressing the repetition of steps 1, 4, and 5b. 
Please let me know if there's anything else we can help with or we can close this.
Thank you!

**Comment by JeffGreenlee42** [comment]
Thank you .. that is all that is needed.  Closing this issue.
