### ISSUE TITLE
Small typo recently introduced, version 2.2.7 should be 2.4.7

### ISSUE THREAD

**Issue by hostep** [AdobeDocs/commerce-knowledge-base.en#51]
About info introduced here: https://github.com/AdobeDocs/commerce-knowledge-base.en/compare/923506e8f7...5c43f48ead
Published url: https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/troubleshooting/site-down-or-unresponsive/revised-patches-for-google-maps-access-loss-on-all-adobe-commerce-versions

It says
> All the merchants on any 2.4.4, 2.4.5, 2.4.6 or **2.2.7** patch version should apply these corresponding patches to their version.

But should say:
> All the merchants on any 2.4.4, 2.4.5, 2.4.6 or **2.4.7** patch version should apply these corresponding patches to their version.

/cc @Zitajanice-27

Thanks!

**Comment by Zitajanice-27** [comment]
Updating it right now, apologies and thank you!

________________________________
From: Pieter Hoste ***@***.***>
Sent: Monday, July 1, 2024 2:03 PM
To: AdobeDocs/commerce-knowledge-base.en ***@***.***>
Cc: Zita Rodricks ***@***.***>; Mention ***@***.***>
Subject: [AdobeDocs/commerce-knowledge-base.en] Small typo recently introduced, version 2.2.7 should be 2.4.7 (Issue #51)


EXTERNAL: Use caution when clicking on links or opening attachments.


About info introduced here: 923506e...5c43f48<https://github.com/AdobeDocs/commerce-knowledge-base.en/compare/923506e8f7...5c43f48ead>
Published url: https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/troubleshooting/site-down-or-unresponsive/revised-patches-for-google-maps-access-loss-on-all-adobe-commerce-versions

It says

All the merchants on any 2.4.4, 2.4.5, 2.4.6 or 2.2.7 patch version should apply these corresponding patches to their version.

But should say:

All the merchants on any 2.4.4, 2.4.5, 2.4.6 or 2.4.7 patch version should apply these corresponding patches to their version.

/cc @Zitajanice-27<https://github.com/Zitajanice-27>

Thanks!

**Comment by hostep** [comment]
Thanks, I can see it's fixed now, closing.
