### ISSUE TITLE
Incorrect service listed in warning banner at top of page

### ISSUE THREAD

**Issue by nlh-ddunn** [AdobeDocs/commerce-knowledge-base.en#7]
Issue in ./help/troubleshooting/database/mysql-high-load-bottleneck-in-magento-commerce-cloud.md

This should be listed as MySQL or Database, not Redis, as Redis is not applicable in this context

**Comment by Rinn22** [comment]
jira ticket: https://jira.corp.adobe.com/browse/MSKB-1888

**Comment by barnato-v** [comment]
@nlh-ddunn Thanks for submitting this update suggestions. I will find a SME to confirm this update.

**Comment by barnato-v** [comment]
@nlh-ddunn Hi - that you so much for your contribution. One of our SMEs confirmed that the note is indeed in the wrong place but would be fine to be moved to under the solution which I have done in the published article here https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/database/mysql-high-load-bottleneck-in-magento-commerce-cloud.html?lang=en

Closing this issue now
