### ISSUE TITLE
Provide additional details on how to Identify long running processes, kill process

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-knowledge-base.en#9]
Issue in ./help/troubleshooting/deployment/magento-deployment-troubleshooter.md

https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/deployment/magento-deployment-troubleshooter.html?lang=en#step-16

More details could be provided on how to ``Identify long running processes, kill process``, for example:

1. Run the command ``ps aufx``
2. Locate the PID of the long-running process (provide an example of the output of the above command
3. Terminate the process using ``kill -9 <PID>``

**Comment by Rinn22** [comment]
jira ticket: https://jira.corp.adobe.com/browse/MSKB-1882

**Comment by barnato-v** [comment]
@ak77-prime thank you for your patience and for taking a long time to response. Our team has been a little snowed under. I will recreate this as a PR in the enterprise/internal repo.

**Comment by barnato-v** [comment]
Change was made https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/deployment/magento-deployment-troubleshooter.html?lang=en#step-16
